name: CurrencyAPI
version: 1.0.0
author: ByteForge88
api: 3.0.0
main: byteforge88\currencyapi\CurrencyAPI

permissions:
  currencyapi.balance:
    default: true
  currencyapi.paymoney:
    default: true
  currencyapi.addmoney:
    default: op
  currencyapi.setmoney:
    default: op
  currencyapi.removemoney:
    default: op